name: manual fly.io app

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'app name'
        default: 'pr-41-sky172839465-integration-example'
        required: true
        type: string
      isDestroy:
        description: 'isDestoryApp'
        required: true
        type: boolean

jobs:
  Destroy:
    if: inputs.isDestroy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Destroy app ${{ inputs.app }}"

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl apps destroy ${{ inputs.app }} --yes --verbose

  Create:
    if: ${{ !inputs.isDestroy }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Create app ${{ inputs.app }}"

      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --yes --verbose
